name: Ruya.Bus.RabbitMQ

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/Ruya.Bus.RabbitMQ.yml'
    - 'src/Ruya.Bus.RabbitMQ/**'

jobs:

  Primitives:

    runs-on: ubuntu-latest

    env:
      buildConfiguration: 'Release'
      buildNumber: '0.0.0'
      projectFile: './src/Ruya.Bus.RabbitMQ/Ruya.Bus.RabbitMQ.csproj'
      projectTestFile: './test/Ruya.Bus.RabbitMQ.Tests/Ruya.Bus.RabbitMQ.Tests.csproj'

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Set the build number
      run: echo ::set-env name=buildNumber::1.1.$(git rev-list --count HEAD)
    - name: Restore
      run: dotnet restore $projectFile
    - name: Build
      run: dotnet build $projectFile --configuration $buildConfiguration -p:BuildNumber=$buildNumber
    - name: Test
      run: dotnet test $projectTestFile --configuration $buildConfiguration -p:CollectCoverage=true
      continue-on-error: true
    - name: Publish
      run: dotnet publish $projectFile --configuration $buildConfiguration --no-restore --no-build --output ./artifacts/staging
    - name: Pack
      run: dotnet pack $projectFile --configuration $buildConfiguration --no-restore --no-build --output ./artifacts/packages
    - name: Tag
      continue-on-error: true
      run: |
        git tag $buildNumber
        authorizationToken=$(echo -n "no-username:${{ secrets.GITHUB_TOKEN }}" | base64)
        git -c http.extraheader="AUTHORIZATION: basic $authorizationToken" push origin $buildNumber
    - name: Set GitHub Release Environment Variables
      run: |
        echo ::set-env name=RELEASE_TAG::$buildNumber
        echo ::set-env name=RELEASE_NAME::$GITHUB_WORKFLOW
        echo ::set-env name=RELEASE_FILES::artifacts-${GITHUB_WORKFLOW}-${buildNumber}:./artifacts/staging ./artifacts/packages/*.nupkg
    - name: GitHub Release
      uses: meeDamian/github-release@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        gzip: folders
        allow_override: true
        prerelease: false
    - name: Nuget
      run: dotnet nuget push ./artifacts/packages/*.nupkg -k ${nugetApiKey} -s https://api.nuget.org/v3/index.json
      env:
        nugetApiKey: ${{secrets.NUGET_API_KEY}}

